### ISSUE TITLE
Great Design 👍, but gradient hurts my eyes 😵

### ISSUE THREAD

**Issue by rocketbear27** [highlowapp/highlowapp.github.io#1]
I really like the design, but the gradient used hurts my eyes after reading stuff on the gradient. It might be just me, but I just wanted to give some feedback.

**Comment by naclcaleb** [comment]
So sorry I didn't realize this issue was here!

The website is definitely in need of a redesign, and we're open to contributions from the community (via pull requests). See [this blog post.](http://gethighlow.com/blog/view/index.html?postId=pzBBryDqQw5FFFkla5y8)

Fortunately for you, the mobile app itself has much less of a gradient presence 😉
Too much gradient can be horrible for design, so we're trying to put it only where it counts.

**Comment by naclcaleb** [comment]
If you'd like to redesign the website, we'd be more than happy to take a contribution!

**Comment by rocketbear27** [comment]
Ok, let me give it a try

**Comment by rocketbear27** [comment]
Finished and created a pull request #3
